version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    environment:
      - MONGO_URL=mongodb://mongo:27017/luma
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    restart: unless-stopped

  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongo-data: {}